name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Lint (ruff)
        run: |
          ruff --version || true
          ruff check .
      - name: Format check (black)
        run: |
          black --check .
      - name: Security audit (pip-audit)
        run: |
          pip-audit -r ../requirements.txt || true
      - name: Run tests
        env:
          PYTHONPATH: "${{ github.workspace }}"
        run: |
          pytest -q
      - name: Export OpenAPI
        run: |
          python ../scripts/tools/export_openapi.py

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint -- --max-warnings=0
      - name: Unit tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit
      - name: Build
        run: npm run build

