name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Lighthouse CI
        run: |
          npm i -g @lhci/cli@0.13.x
      - name: Prepare environment
        env:
          STAGING_FRONTEND_URL: ${{ vars.STAGING_FRONTEND_URL }}
          LHCI_SERVER_BASE_URL: ${{ vars.LHCI_SERVER_BASE_URL }}
          LHCI_TOKEN: ${{ secrets[vars.LHCI_TOKEN_KEY] }}
        run: |
          echo "TARGET_URL=$STAGING_FRONTEND_URL" >> $GITHUB_ENV
          echo "LHCI_SERVER_BASE_URL=$LHCI_SERVER_BASE_URL" >> $GITHUB_ENV
          echo "LHCI_TOKEN=$LHCI_TOKEN" >> $GITHUB_ENV
      - name: Run Lighthouse (mobile)
        run: |
          lhci autorun --collect.url="$TARGET_URL" --collect.settings.preset=mobile --assert.assertions.performance=error:85 --assert.assertions.accessibility=error:90 --assert.assertions."best-practices"=error:90 || true
      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci

